apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-1
  labels:
    type: local
spec:
    storageClassName: mysql-storage
    capacity:
      storage: 50Mi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: /shiva/mysql-db/traderapp-kubernetes