apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-1
spec:
  storageClassName: mysql-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi

