server:
  port: 8082
spring:
  application:
    name: customerordermanagement
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka.server}