spring:
  application:
    name: ApiGateway
server:
  port: 9200
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.server}
zuul:
  sensitive-headers:
  routes:
    authenticate-service:
      path: /api/login
      serviceId: LoginService
    customer-management:
      path: customermanagement/**
      serviceId: customermanagement
    customer-ordermanagement:
      path: customerordermanagement/**
      serviceId: customerordermanagement
#    customer-management1:
#      path: /api/user/**
#      serviceId: customermanagement,
#      stripPrefix: false
#      sensitiveHeaders:
#    customer-management2:
#      path: /api/registration
#      serviceId: customermanagement,
#      stripPrefix: false
#    customer-management3:
#      path: /api/registration/**
#      serviceId: customermanagement,
#      stripPrefix: false
