apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ordermanagement-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /customermanagement
            pathType: Prefix
            backend:
              service:
                name: customermanagement
                port:
                  number: 80
          - path: /customerordermanagement
            pathType: Prefix
            backend:
              service:
                name: customerordermanagement
                port:
                  number: 80
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: authenticationservice
                port:
                  number: 80