apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ordermanagement-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
spec:
  rules:
    - http:
        paths:
          - path: /customermanagement/api(/|$)(.*)
            pathType: Prefix
            backend:
              serviceName: customermanagement
              servicePort: 80
          - path: /customerordermanagement
            pathType: Prefix
            backend:
              serviceName: customerordermanagement
              servicePort: 80
          - path: /auth
            pathType: Prefix
            backend:
              serviceName: authenticationservice
              servicePort: 80